const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';


//signup
const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL';

const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST';
const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
const GET_USER_INFO_FAIL = 'GET_USER_INFO_FAIL';

const UPDATE_USER_INFO_REQUEST = 'UPDATE_USER_INFO_REQUEST';
const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS';
const UPDATE_USER_INFO_FAIL = 'UPDATE_USER_INFO_FAIL';

const    GENERATE_IMAGE_REQUEST='GENERATE_IMAGE_REQUEST';
const    GENERATE_IMAGE_SUCCESS='GENERATE_IMAGE_SUCCESS';
const    GENERATE_IMAGE_FAIL='GENERATE_IMAGE_FAIL';

const    SHOW_GENERATED_IMAGE_REQUEST='SHOW_GENERATED_IMAGE_REQUEST';
const    SHOW_GENERATED_IMAGE_SUCCESS='SHOW_GENERATED_IMAGE_SUCCESS';
const    SHOW_GENERATED_IMAGE_FAIL='SHOW_GENERATED_IMAGE_FAIL';

const DELETE_ALL_IMAGES_REQUEST = 'DELETE_ALL_IMAGES_REQUEST';
const DELETE_ALL_IMAGES_SUCCESS = 'DELETE_ALL_IMAGES_SUCCESS';
const DELETE_ALL_IMAGES_FAILURE = 'DELETE_ALL_IMAGES_FAILURE';

 const MOVE_IMAGES_REQUEST = 'MOVE_IMAGES_REQUEST';
 const MOVE_IMAGES_SUCCESS = 'MOVE_IMAGES_SUCCESS';
 const MOVE_IMAGES_FAILURE = 'MOVE_IMAGES_FAILURE';


const CREATE_IMAGES_REQUEST = 'CREATE_IMAGES_REQUEST';
const CREATE_IMAGES_SUCCESS = 'CREATE_IMAGES_SUCCESS';
const CREATE_IMAGES_FAILURE = 'CREATE_IMAGES_FAILURE';


const RESET_GENERATED_IMAGES = "RESET_GENERATED_IMAGES";

const SHOW_IMAGES_REQUEST = 'SHOW_IMAGES_REQUEST';
const SHOW_IMAGES_SUCCESS = 'SHOW_IMAGES_SUCCESS';
const SHOW_IMAGES_FAILURE = 'SHOW_IMAGES_FAILURE';


const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';


const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST"
const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS"
const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE"

const GET_ALL_ACCOUNT_REQUEST = "GET_ALL_ACCOUNT_REQUEST";
const GET_ALL_ACCOUNT_SUCCESS = "GET_ALL_ACCOUNT_SUCCESS";
const GET_ALL_ACCOUNT_FAILURE = "GET_ALL_ACCOUNT_FAILURE";
const UPDATE_REQUEST = "UPDATE_REQUEST";
const UPDATE_SUCCESS = "UPDATE_SUCCESS";
const UPDATE_FAILURE = "UPDATE_FAILURE";



const DELETE_REQUEST = "DELETE_REQUEST";
const DELETE_SUCCESS = "DELETE_SUCCESS";
const DELETE_FAILURE = "DELETE_FAILURE";

const ADD_NEW_ACCOUNT_REQUEST = "ADD_NEW_ACCOUNT_REQUEST";
const ADD_NEW_ACCOUNT_SUCCESS = "ADD_NEW_ACCOUNT_SUCCESS";
const ADD_NEW_ACCOUNT_FAIL = "ADD_NEW_ACCOUNT_FAIL";
const actionTypes ={
    USER_SIGNIN_REQUEST,
    USER_SIGNIN_SUCCESS,
    USER_SIGNIN_FAIL,

    USER_SIGNUP_REQUEST,
    USER_SIGNUP_SUCCESS,
    USER_SIGNUP_FAIL,

    GET_USER_INFO_REQUEST,
    GET_USER_INFO_SUCCESS,
    GET_USER_INFO_FAIL,

    UPDATE_USER_INFO_REQUEST,
    UPDATE_USER_INFO_SUCCESS,
    UPDATE_USER_INFO_FAIL,

    ADD_NEW_ACCOUNT_REQUEST,
    ADD_NEW_ACCOUNT_SUCCESS,
    ADD_NEW_ACCOUNT_FAIL,

    GENERATE_IMAGE_REQUEST,
    GENERATE_IMAGE_SUCCESS,
    GENERATE_IMAGE_FAIL,

    SHOW_GENERATED_IMAGE_REQUEST,
    SHOW_GENERATED_IMAGE_SUCCESS,
    SHOW_GENERATED_IMAGE_FAIL,

    DELETE_ALL_IMAGES_REQUEST,
    DELETE_ALL_IMAGES_SUCCESS,
    DELETE_ALL_IMAGES_FAILURE,

    MOVE_IMAGES_REQUEST,
    MOVE_IMAGES_SUCCESS,
    MOVE_IMAGES_FAILURE,

    CREATE_IMAGES_REQUEST,
    CREATE_IMAGES_SUCCESS,
    CREATE_IMAGES_FAILURE,


    RESET_GENERATED_IMAGES,

    SHOW_IMAGES_REQUEST,
    SHOW_IMAGES_SUCCESS,
    SHOW_IMAGES_FAILURE,


    CHANGE_PASSWORD_REQUEST,
    CHANGE_PASSWORD_SUCCESS,
    CHANGE_PASSWORD_FAILURE,


    GET_ALL_ACCOUNT_REQUEST,
    GET_ALL_ACCOUNT_SUCCESS,
    GET_ALL_ACCOUNT_FAILURE,


    RESET_PASSWORD_REQUEST,
    RESET_PASSWORD_SUCCESS,
    RESET_PASSWORD_FAILURE,

    UPDATE_REQUEST,
    UPDATE_SUCCESS,
    UPDATE_FAILURE,


    DELETE_REQUEST,
    DELETE_SUCCESS,
    DELETE_FAILURE,


}

export default actionTypes;